title : Ahmed Alaa
logo : assets/zes.jpg
description: <div class="social-links">
    <a href="https://www.linkedin.com/in/ahmed-alaa-4b74b2279" target="_blank" title="LinkedIn"><i class="fab fa-linkedin"></i></a>
    <a href="https://github.com/Ahmed-alaa47" target="_blank" title="GitHub"><i class="fab fa-github"></i></a>
    <a href="mailto:ahmeda.elhousseny@gmail.com" target="_blank" title="Email"><i class="fas fa-envelope"></i></a>
  </div>
show downloads : true
theme: jekyll-theme-minimal
